### ISSUE TITLE
Trading Bot Page

### ISSUE THREAD

**Issue by JScheire** [RiyaTayal20/SEP_SMFLSpring2021#120]
Trading bot page to teach players about the bot's decision making

**Comment by christinem61** [comment]
Individual Stock Page:
- Added a lightbulb button that takes user to ai page
![image](https://user-images.githubusercontent.com/59708808/115452388-5b3cd800-a1ec-11eb-9480-4fb4cefd3a16.png)

AI Page:
- shows how each algorithm would have traded stock w data from the past year based on technical indicators
![image](https://user-images.githubusercontent.com/59708808/115452547-90492a80-a1ec-11eb-8988-80b44b4e28dc.png)
