### ISSUE TITLE
[SAPI] Create historical and intraday prices endpoints

### ISSUE THREAD

**Issue by JScheire** [RiyaTayal20/SEP_SMFLSpring2021#15]
Create SAPI endpoint to pull price data from IEX cloud upon user request. This data should be in a format where it can be easily graphed. See #16.

Reference: 
https://iexcloud.io/docs/api/#historical-prices

**Comment by avidlaud** [comment]
- [ ] Query intraday data and store into database
- [ ] Provide intraday price endpoint
- [ ] Query historical data and store into database
- [ ] Provide historical price endpoint

**Comment by avidlaud** [comment]
Completed with #38.
