### ISSUE TITLE
Portfolio Component + Page

### ISSUE THREAD

**Issue by JScheire** [RiyaTayal20/SEP_SMFLSpring2021#35]
Create page and any relevant components that allows the user to view their portfolio on the front end, which includes their portfolio value as well as their current positions.

![Screenshot](https://user-images.githubusercontent.com/29742300/111807397-485f7c80-88a9-11eb-8efe-c4fb6b0964a4.png)

**Comment by avidlaud** [comment]
Positions mostly complete, graph still required.

**Comment by JScheire** [comment]
To-do:
- [ ] Total return
- [ ] Return since last close for portfolio
- [ ] Return since last close for each holding
