### ISSUE TITLE
Individual Stocks Page

### ISSUE THREAD

**Issue by JScheire** [RiyaTayal20/SEP_SMFLSpring2021#47]
Create individual stocks page for stock research

![image](https://user-images.githubusercontent.com/29742300/112231961-1d10c080-8c0e-11eb-8e67-a9e88e4d0ce9.png)

**Comment by christinem61** [comment]
- [ ] current price
- [ ] stock research/statistics
- [ ] graph tab component

**Comment by christinem61** [comment]
instead of tabs, used buttons:
![image](https://user-images.githubusercontent.com/59708808/112393233-231ba580-8cd1-11eb-8e30-5e33d6830d8e.png)
