### ISSUE TITLE
Fix frontend styling to be more consistent across screen sizes

### ISSUE THREAD

**Issue by JScheire** [RiyaTayal20/SEP_SMFLSpring2021#61]
Some of the styling for the frontend has a hard time conforming to different screen sizes. Make use of flexboxes and more percentage values to help with this issue. You can test this by inspecting element/F12 and choosing mobile view, which allows you to resize the screen.

**Comment by Anirudh-GH** [comment]
Can I work on this issue

**Comment by JScheire** [comment]
> Can I work on this issue

Hi Anirudh,

This is a school project.

**Comment by Anirudh-GH** [comment]
Sure not a problem
